Repository WildCodeSchool-2024-09/toulouse-p2-cinewild, pull requests merged in 2024-11, with the labels that each got.

#3 feat(App.tsx): add michel to title
  client/src/App.tsx
Labels: CORRECTIONS_DONE, REVIEWD

#5 feat: add p
  client/src/App.tsx
Labels: CORRECTIONS_DONE, REVIEWD

#6 feat: add my name
  client/src/App.tsx
Labels: CORRECTIONS_DONE, REVIEWD

#7 feat: component searchBar
  client/src/App.css
  client/src/App.tsx
  client/src/assets/images/background.webp
  client/src/assets/images/icon-loupe.svg
  client/src/assets/styles/FilmSearchBar.css
  client/src/components/FilmSearchBar.tsx
  client/src/main.tsx
  client/src/styles.css
  package-lock.json
Labels: CONFLICTS_RESOLVED, REVIEWD

#10 fix: fix all main problems
  client/src/App.css
  client/src/assets/styles/Background.css
  client/src/assets/styles/ButtonBurger.css
  client/src/assets/styles/Card.css
  client/src/assets/styles/FilmSearchBar.css
  client/src/assets/styles/Genre.css
  client/src/assets/styles/HomeScreen.css
  client/src/assets/styles/MenuBurger.css
  client/src/assets/styles/MiniCard.css
  client/src/assets/styles/Years.css
  client/src/components/Card.tsx
  client/src/components/HomeScreen.tsx
Labels: REVIEWD

#12 feat: add favorite
  client/package.json
  client/src/App.tsx
  client/src/assets/styles/ButtonBurger.css
  client/src/assets/styles/Card.css
  client/src/assets/styles/MenuBurger.css
  client/src/components/Card.tsx
  client/src/components/FavoritesContext.tsx
  client/src/components/HomeScreen.tsx
Labels: CONFLICTS_RESOLVED, REVIEWD

#13 fix: add style
  client/src/assets/styles/Card.css
  client/src/assets/styles/Genre.css
  client/src/assets/styles/MenuBurger.css
  client/src/assets/styles/Years.css
  client/src/components/Genre.tsx
Labels: REVIEWD

#14 S2 us11/footer
  client/src/assets/images/pas-image-film.svg
  client/src/assets/images/pas-image-film2.svg
  client/src/assets/styles/ButtonBurger.css
  client/src/assets/styles/MenuBurger.css
  client/src/assets/styles/ModalContactForm.css
  client/src/components/HomeScreen.tsx
  client/src/components/ModalContactForm.tsx
Labels: REVIEWD

#15 S3 us17/favoritelist
  client/src/App.tsx
  client/src/components/ButtonBurger.tsx
  client/src/components/Card.tsx
  client/src/components/FavoritesPage.tsx
  client/src/components/HomeScreen.tsx
  client/src/components/MenuBurger.tsx
  client/src/context/FavoritesContext.tsx
  client/src/context/GenreContext.tsx
  client/src/main.tsx
  client/src/types/interface.ts
Labels: REVIEWD

#16 S2 us17/image
  client/src/assets/images/pas-image-film.svg
  client/src/assets/images/pas-image-film2.svg
  client/src/assets/images/sans-image.svg
  client/src/components/Card.tsx
  client/src/components/MiniCard.tsx
Labels: REVIEWD

#17 S3 us15/loader
  client/package.json
  client/src/App.css
  client/src/assets/images/defaultCardImg.png
  client/src/assets/styles/Card.css
  client/src/assets/styles/HomeScreen.css
  client/src/assets/styles/MiniCard.css
  client/src/assets/styles/ModalContactForm.css
  client/src/components/Card.tsx
  client/src/components/FilmSearchBar.tsx
  client/src/components/Genre.tsx
  client/src/components/HomeScreen.tsx
  client/src/components/MenuBurger.tsx
  client/src/components/MiniCard.tsx
  client/src/components/ModalContactForm.tsx
  client/src/components/Years.tsx
  client/src/context/FavoritesContext.tsx
Labels: CONFLICTS_RESOLVED, REVIEWD

#18 feat: create favicon
  client/index.html
  client/public/favicon.ico
  client/public/vite.svg
Labels: REVIEWD

#19 S3 us16/media queries
  client/src/App.css
  client/src/assets/styles/ButtonBurger.css
  client/src/assets/styles/Card.css
  client/src/assets/styles/FilmSearchBar.css
  client/src/assets/styles/Genre.css
  client/src/assets/styles/HomeScreen.css
  client/src/assets/styles/MenuBurger.css
  client/src/assets/styles/MiniCard.css
  client/src/assets/styles/Years.css
  client/src/components/ButtonBurger.tsx
  client/src/components/Card.tsx
  client/src/components/HomeScreen.tsx
  client/src/components/MenuBurger.tsx
  package-lock.json
Labels: REVIEWD
